'use client';
import {useState} from 'react'; import {useRouter} from 'next/navigation';
import {bookSchema,clauseSchema} from '@/lib/validation/schemas'; import {definitionHash,ClauseDraft} from '@/lib/genlayer/definition';
import {matchingClause,matchingDraft} from '@/lib/genlayer/draft-recovery'; import {useWallet} from '@/lib/wallet/provider';
import {addresses,latestRulebook,readBook,readClause} from '@/lib/genlayer/contracts'; import {submitAndConfirm,TxState} from '@/lib/genlayer/transaction'; import {TxStatus} from './tx-status';
const empty=():ClauseDraft=>({label:'',prose:'',severity:'REQUIRED',evidenceNeed:'PUBLIC_URL'});
export function Composer(){
 const router=useRouter(),wallet=useWallet(); const [title,setTitle]=useState(''),[purpose,setPurpose]=useState(''),[resource,setResource]=useState(''),[maxDuration,setMaxDuration]=useState('604800'),[cooldown,setCooldown]=useState('86400'),[clauses,setClauses]=useState<ClauseDraft[]>([empty()]),[error,setError]=useState(''),[tx,setTx]=useState<TxState>({phase:'IDLE'});
 const update=(i:number,k:keyof ClauseDraft,v:string)=>setClauses(xs=>xs.map((x,n)=>n===i?{...x,[k]:v}:x));
 const publish=async()=>{try{const draft={title,purpose,resource,maxDuration,cooldown,maxEvidence:3,clauses};bookSchema.parse(draft);if(!wallet.client||!wallet.account||!wallet.onStudionet)throw new Error('Connect Studionet wallet.');let id=await latestRulebook(wallet.account),book=id?await readBook(id):null;
  if(book&&!matchingDraft(book,draft)){id=0n;book=null} // Never seal a same-title but different draft.
  if(!book){const created=await submitAndConfirm(wallet.client,{address:addresses.book,functionName:'create_rulebook',args:[title,purpose,resource,BigInt(maxDuration),BigInt(cooldown),3n,'']},async()=>{id=await latestRulebook(wallet.account!);book=await readBook(id);return !!book&&matchingDraft(book,draft)&&book.creator.toLowerCase()===wallet.account!.toLowerCase()},setTx);if(!created.ok)return}
  for(let i=0;i<clauses.length;i++){const clause=clauses[i];clauseSchema.parse(clause);const current=await readBook(id);if(Number(current.clause_count)>i){if(!matchingClause(await readClause(id,BigInt(i+1)),clause,i))throw new Error('Existing draft clause differs from this definition; it will not be sealed.');continue}const added=await submitAndConfirm(wallet.client,{address:addresses.book,functionName:'add_clause',args:[id,clause.label,clause.prose,clause.severity,clause.evidenceNeed]},async()=>matchingClause(await readClause(id,BigInt(i+1)),clause,i),setTx);if(!added.ok)return}
  const hash=await definitionHash(draft);const sealed=await submitAndConfirm(wallet.client,{address:addresses.book,functionName:'seal',args:[id]},async()=>{const on=await readBook(id);return on.status==='SEALED'&&Number(on.clause_count)===clauses.length&&on.definition_hash===hash},setTx);if(sealed.ok)router.push(`/b/${id}`)
 }catch(e:any){setError(e.issues?.[0]?.message||e.message)}};
 return <><div className="paper"><label>Title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Purpose<textarea value={purpose} onChange={e=>setPurpose(e.target.value)}/></label><label>Resource<input value={resource} onChange={e=>setResource(e.target.value)}/></label><label>Maximum duration<input value={maxDuration} onChange={e=>setMaxDuration(e.target.value)}/></label><label>Cooldown<input value={cooldown} onChange={e=>setCooldown(e.target.value)}/></label>{clauses.map((c,i)=><div className="clause" key={i}><input placeholder="Label" value={c.label} onChange={e=>update(i,'label',e.target.value)}/><textarea placeholder="Rule" value={c.prose} onChange={e=>update(i,'prose',e.target.value)}/><select value={c.severity} onChange={e=>update(i,'severity',e.target.value)}><option>REQUIRED</option><option>EXCLUSION</option><option>PREFERENCE</option></select><select value={c.evidenceNeed} onChange={e=>update(i,'evidenceNeed',e.target.value)}><option>PUBLIC_URL</option><option>OPTIONAL_URL</option><option>NONE</option></select></div>)}<button className="secondary" onClick={()=>setClauses([...clauses,empty()])}>Add clause</button>{error&&<p>{error}</p>}<p><button onClick={publish}>Create, add rules, and seal</button></p></div><TxStatus state={tx}/></>}
