import { z } from 'zod';
export const severity = z.enum(['REQUIRED','EXCLUSION','PREFERENCE']);
export const evidenceNeed = z.enum(['NONE','PUBLIC_URL','OPTIONAL_URL']);
export const clauseSchema = z.object({label:z.string().trim().min(2).max(60), prose:z.string().trim().min(12).max(900), severity, evidenceNeed});
export const seconds=z.string().regex(/^\d+$/).refine(v=>BigInt(v)>0n&&BigInt(v)<=31536000n,'Use 1–31536000 seconds.');
export const bookSchema = z.object({title:z.string().trim().min(3).max(80),purpose:z.string().trim().min(10).max(600),resource:z.string().trim().min(2).max(80),maxDuration:seconds,cooldown:z.string().regex(/^\d+$/).refine(v=>BigInt(v)<=31536000n,'Use at most 31536000 seconds.'),maxEvidence:z.coerce.number().int().min(1).max(6),clauses:z.array(clauseSchema).min(1).max(12)});
export const applicationSchema=z.object({statement:z.string().trim().min(8).max(1000),duration:seconds});
const privateIpv4=(h:string)=>{const p=h.split('.').map(Number);return p.length===4&&p.every(n=>Number.isInteger(n)&&n>=0&&n<=255)&&((p[0]===10)||(p[0]===127)||(p[0]===169&&p[1]===254)||(p[0]===192&&p[1]===168)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===100&&p[1]>=64&&p[1]<=127));};
export const httpsUrl = z.string().max(400).refine(v=>{try {const u=new URL(v),h=u.hostname.toLowerCase().replace(/\.$/,'');const labels=h.split('.');const ipv6=h.includes(':');const dns=labels.length>=2&&labels.every(x=>/^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/i.test(x))&&/[a-z]/i.test(labels.at(-1)!);return u.protocol==='https:'&&!u.username&&!u.password&&!u.hash&&!!u.hostname&&u.port===''&&!(h==='localhost'||h.endsWith('.localhost')||h.endsWith('.local'))&&!privateIpv4(h)&&!ipv6&&dns;}catch{return false;}}, 'Use a public HTTPS URL without credentials, fragments, private hosts, or custom ports.');
