import { z } from 'zod';
export const severity = z.enum(['REQUIRED','EXCLUSION','PREFERENCE']);
export const evidenceNeed = z.enum(['NONE','PUBLIC_URL','OPTIONAL_URL']);
export const clauseSchema = z.object({label:z.string().trim().min(2).max(60), prose:z.string().trim().min(12).max(900), severity, evidenceNeed});
export const seconds=z.string().regex(/^\d+$/).refine(v=>BigInt(v)>0n&&BigInt(v)<=31536000n,'Use 1–31536000 seconds.');
export const bookSchema = z.object({title:z.string().trim().min(3).max(80),purpose:z.string().trim().min(10).max(600),resource:z.string().trim().min(2).max(80),maxDuration:seconds,cooldown:z.string().regex(/^\d+$/).refine(v=>BigInt(v)<=31536000n,'Use at most 31536000 seconds.'),maxEvidence:z.coerce.number().int().min(1).max(6),clauses:z.array(clauseSchema).min(1).max(12)});
export const applicationSchema=z.object({statement:z.string().trim().min(8).max(1000),duration:seconds});
const publicIpv4=(h:string)=>{const p=h.split('.').map(Number);if(p.length!==4||!p.every(n=>Number.isInteger(n)&&n>=0&&n<=255))return false;const[a,b,c,d]=p;const special192=a===192&&b===0&&!(c===0&&(d===9||d===10));return !(a===0||a===10||a===100&&b>=64&&b<=127||a===127||a===169&&b===254||a===172&&b>=16&&b<=31||special192||a===192&&b===168||a===198&&(b===18||b===19||b===51)||a===203&&b===0||a>=224);};
export const httpsUrl = z.string().max(400).refine(v=>{try {const authority=/^[a-z][a-z0-9+.-]*:\/\/([^/?#]*)/i.exec(v)?.[1];if(!authority||/[^\x00-\x7F]/.test(authority))return false;const u=new URL(v),h=u.hostname.toLowerCase().replace(/\.$/,'');const labels=h.split('.');const ipv4=/^\d+\.\d+\.\d+\.\d+$/.test(h);const dns=labels.length>=2&&labels.every(x=>/^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$/i.test(x))&&/[a-z]/i.test(labels.at(-1)!);return u.protocol==='https:'&&!u.username&&!u.password&&!u.hash&&!!u.hostname&&u.port===''&&!(h==='localhost'||h.endsWith('.localhost')||h.endsWith('.local'))&&(!ipv4||publicIpv4(h))&&!h.includes(':')&&(ipv4||dns);}catch{return false;}}, 'Use a public HTTPS URL without credentials, fragments, private hosts, or custom ports.');
