'use client';
import { createContext, useContext, useEffect, useState } from 'react';
import { createClient } from 'genlayer-js';
import { studionet } from 'genlayer-js/chains';
import { isStudionet, STUDIONET } from '@/lib/genlayer/network';
type Provider={request(a:{method:string;params?:unknown[]}):Promise<any>;on(e:string,c:(...x:any[])=>void):void;removeListener(e:string,c:(...x:any[])=>void):void};
type Wallet={account?:`0x${string}`;chainId?:string;client?:any;connected:boolean;connecting:boolean;error?:string;onStudionet:boolean;connect():Promise<void>;disconnect():void;switchNetwork():Promise<void>};
const Context=createContext<Wallet|null>(null);
async function switchTo(p:Provider){const chainId='0xf22f';try{await p.request({method:'wallet_switchEthereumChain',params:[{chainId}]});}catch(e:any){if(e?.code!==4902)throw e;await p.request({method:'wallet_addEthereumChain',params:[{chainId,chainName:STUDIONET.name,nativeCurrency:{name:'GEN',symbol:'GEN',decimals:18},rpcUrls:[STUDIONET.rpcUrl],blockExplorerUrls:[STUDIONET.explorer]}]});}}
export function WalletProvider({children}:{children:React.ReactNode}){const [account,setAccount]=useState<`0x${string}`>();const [chainId,setChain]=useState<string>();const [connecting,setConnecting]=useState(false);const [error,setError]=useState<string>();const p=typeof window==='undefined'?undefined:(window as any).ethereum as Provider|undefined;const sync=async()=>{if(!p)return;const [accounts,chain]=await Promise.all([p.request({method:'eth_accounts'}),p.request({method:'eth_chainId'})]);setAccount(accounts[0]);setChain(chain);};useEffect(()=>{if(!p)return;void p.request({method:'eth_accounts'}).then(a=>setAccount(a[0]));void p.request({method:'eth_chainId'}).then(setChain);const ac=(a:string[])=>setAccount(a[0] as `0x${string}`);const ch=(x:string)=>setChain(x);const dc=()=>setAccount(undefined);p.on('accountsChanged',ac);p.on('chainChanged',ch);p.on('disconnect',dc);return()=>{p.removeListener('accountsChanged',ac);p.removeListener('chainChanged',ch);p.removeListener('disconnect',dc)}},[p]);const connect=async()=>{if(!p){setError('No injected wallet was found.');return;}setConnecting(true);setError(undefined);try{await p.request({method:'eth_requestAccounts'});await switchTo(p);await sync();}catch(e){setError(e instanceof Error?e.message:'Wallet connection was rejected.');}finally{setConnecting(false);}};const switchNetwork=async()=>{if(!p)return;try{await switchTo(p);await sync();}catch(e){setError(e instanceof Error?e.message:'Could not switch to Studionet.');}};return <Context.Provider value={{account,chainId,client:p&&account?createClient({chain:studionet,account,provider:p}):undefined,connected:!!account,connecting,error,onStudionet:isStudionet(chainId),connect,disconnect:()=>setAccount(undefined),switchNetwork}}>{children}</Context.Provider>};
export const useWallet=()=>{const x=useContext(Context);if(!x)throw new Error('WalletProvider missing');return x};
