'use client';
import {useEffect,useState} from 'react';
import {useWallet} from '@/lib/wallet/provider';
import {applicationCount,isAuthorized,passByEvaluation,readApplication,readEvaluation} from '@/lib/genlayer/contracts';

type RecordItem={application:any;evaluation?:any;pass?:any;authorized?:boolean};
export default function Me(){
  const wallet=useWallet(),[records,setRecords]=useState<RecordItem[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false);
  const refresh=async()=>{if(!wallet.account)return;setLoading(true);setError('');try{const total=Number(await applicationCount());const all=await Promise.all(Array.from({length:total},(_,i)=>readApplication(BigInt(i+1))));const mine=all.filter(a=>String(a.applicant).toLowerCase()===wallet.account!.toLowerCase());const resolved=await Promise.all(mine.map(async application=>{const evaluation=application.evaluation_id?await readEvaluation(BigInt(application.evaluation_id)):undefined;const pass=evaluation?await passByEvaluation(BigInt(evaluation.id)):undefined;const authorized=pass?.id?await isAuthorized(BigInt(application.rulebook_id),wallet.account!):false;return {application,evaluation,pass:pass?.id?pass:undefined,authorized}}));setRecords(resolved)}catch(e:any){setError(e.message||'Could not load canonical records.')}finally{setLoading(false)}};
  useEffect(()=>{void refresh()},[wallet.account]);
  return <main><span className="eyebrow">Wallet records</span><h2>Your applications<br/>and passes.</h2><div className="paper"><p>Connected wallet: {wallet.account||'not connected'}</p><button onClick={refresh} disabled={!wallet.account||loading}>{loading?'Refreshing canonical state…':'Refresh records'}</button>{error&&<p>{error}</p>}{wallet.account&&records.length===0&&!loading&&<p>No submitted Ruleloom applications were found for this wallet.</p>}{records.map(({application,evaluation,pass,authorized})=><section className="receipt" key={application.id}><h3>Application #{application.id} · Rulebook #{application.rulebook_id}</h3><p>Status: {application.status}</p>{evaluation&&<p>Evaluation #{evaluation.id}: {evaluation.decision} {evaluation.issued?'· issued':'· not issued'}</p>}{pass&&<><p>Pass #{pass.id}: {pass.active?'stored active':'inactive'} · expiry {new Date(Number(pass.expiry)*1000).toLocaleString()}</p><p className="decision">{authorized?'AUTHORIZED':'NOT AUTHORIZED'}</p></>}{evaluation?.decision==='ALLOW'&&String(evaluation.applicant).toLowerCase()!==wallet.account?.toLowerCase()&&<p>Only applicant {evaluation.applicant} can issue this pass.</p>}</section>)}</div></main>
}
